on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to echo"
        required: true
      execution_id:
        description: "Reference id"
        required: true
  pull_request:

run-name: Hello ${{ inputs.execution_id }}

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 30 seconds
        run: sleep 30
        shell: bash
      - name: Echo Message
        run: echo "${{ inputs.message }}"
